version: '3'

services:
  pg-example:
    image: postgres:14.1-alpine3.15
    container_name: pg-example
    environment:
      - POSTGRES_USER=marcus
      - POSTGRES_PASSWORD=marcus
      - POSTGRES_DB=application
    volumes:
      - ./db/structure.sql:/docker-entrypoint-initdb.d/1.sql
      - ./db/data.sql:/docker-entrypoint-initdb.d/2.sql
    ports:
      - 127.0.0.1:5432:5432
    restart: always

  redis-example:
    image: redis:alpine
    container_name: redis-example
    ports:
      - 127.0.0.1:6379:6379
    restart: always
networks:
  default:
    name: api-example-network
